### ISSUE TITLE
The results of vscode-tmgrammar-test do not match "Inspect Editor Tokens and Scopes".

### ISSUE THREAD

**Issue by isao-takejib** [e-bigmoon/vscode-language-yesod#27]
- The results of vscode-tmgrammar-test do not match the results of VSCode's "Inspect Editor Tokens and Scopes".
    - VSCode's "Inspect Editor Tokens and Scopes"
    ![image](https://user-images.githubusercontent.com/61075211/114265670-26cb5e00-9a2d-11eb-8b07-5e0227f298dc.png)
    ![image](https://user-images.githubusercontent.com/61075211/114265714-55493900-9a2d-11eb-99b2-58920593f2c0.png)
    ![image](https://user-images.githubusercontent.com/61075211/114265733-6c882680-9a2d-11eb-8be4-41d04e24d399.png)
    - vscode-tmgrammar-snap
      ```
      ><head>
      #^^^^^ source.yesod.hamlet meta.embedded.line.hamlet
      #     ^ source.yesod.hamlet meta.embedded.line.hamlet
      >    <title>#{title}
      #^^^^ source.yesod.hamlet
      #    ^^^^^^ source.yesod.hamlet meta.embedded.line.hamlet
      #          ^ source.yesod.hamlet meta.embedded.line.hamlet
      #           ^^^^^^^^^ source.yesod.hamlet
      >
      ```

**Comment by isao-takejib** [comment]
The following screenshot is after the merge of #23. (There is no change in the defect.)

- VSCode (ver1.56.2)

![image](https://user-images.githubusercontent.com/61075211/119217435-238bbd80-bb15-11eb-8c81-09dad508e1e3.png)
![image](https://user-images.githubusercontent.com/61075211/119217441-37cfba80-bb15-11eb-8f4d-aad38d8b8426.png)
![image](https://user-images.githubusercontent.com/61075211/119217455-4c13b780-bb15-11eb-84b9-4a5f3d702552.png)

- vscode-tmgrammar-snap ver0.0.10 (+ vscode-textmate ver4.4.0)

```
><head>
#^ source.yesod.hamlet meta.tag.hamlet punctuation.definition.tag.begin.hamlet
# ^^^^ source.yesod.hamlet meta.tag.hamlet entity.name.tag.hamlet
#     ^ source.yesod.hamlet meta.tag.hamlet punctuation.definition.tag.end.hamlet
>    <title>#{title}
#^^^^ source.yesod.hamlet
#    ^ source.yesod.hamlet meta.tag.hamlet punctuation.definition.tag.begin.hamlet
#     ^^^^^ source.yesod.hamlet meta.tag.hamlet entity.name.tag.hamlet
#          ^ source.yesod.hamlet meta.tag.hamlet punctuation.definition.tag.end.hamlet
#           ^^^^^^^^^ source.yesod.hamlet
>
```

**Comment by isao-takejib** [comment]
The following sample is used. (In this example, the name is `test2.hamlet`.)
```
$# SYNTAX TEST "source.yesod.hamlet" "interpolation"
<head>
$# <-  meta.tag.hamlet punctuation.definition.tag.begin.hamlet
$# <~----  meta.tag.hamlet entity.name.tag.hamlet
$#   ^  meta.tag.hamlet punctuation.definition.tag.end.hamlet
    <title>#{title}
$#  ^  meta.tag.hamlet punctuation.definition.tag.begin.hamlet
$#   ^^^^^  meta.tag.hamlet entity.name.tag.hamlet
$#        ^  meta.tag.hamlet punctuation.definition.tag.end.hamlet
$#         ^^  meta.interpolation.hamlet punctuation.section.interpolation.begin.hamlet
$#           ^^^^^  meta.interpolation.hamlet source.haskell.embedded
$#                ^  meta.interpolation.hamlet punctuation.section.interpolation.end.hamlet
```

### Result of vscode-tmgrammar-snap

`$ npx vscode-tmgrammar-test -s source.yesod.hamlet -g syntaxes/hamlet.tmLanguage.json -t "test2.hamlet"`

```
$ npx vscode-tmgrammar-test -s source.yesod.hamlet -g syntaxes/hamlet.tmLanguage.json -t "./test2.hamlet"
grammar not found for 'source.haskell'
✖ ./test2.hamlet failed
  at [./test2.hamlet:6:12:21]: 
  6:     <title>#{title}
                ^^^^^^^^^
  missing required scopes: meta.interpolation.hamlet punctuation.section.interpolation.begin.hamlet
  actual: source.yesod.hamlet


  at [./test2.hamlet:6:12:21]: 
  6:     <title>#{title}
                ^^^^^^^^^
  missing required scopes: meta.interpolation.hamlet source.haskell.embedded
  actual: source.yesod.hamlet


  at [./test2.hamlet:6:12:21]: 
  6:     <title>#{title}
                ^^^^^^^^^
  missing required scopes: meta.interpolation.hamlet punctuation.section.interpolation.end.hamlet
  actual: source.yesod.hamlet
```

**Comment by isao-takejib** [comment]
```
$ npx vscode-tmgrammar-test -s source.yesod.hamlet -g syntaxes/hamlet.tmLanguage.json -g haskell.tmLanguage.json -t "./test2.hamlet"
✖ testcase ./test2.hamlet aborted due to an error
Error: invalid pattern in look-behind
    at Object.createOnigScanner (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:67:24)
    at Grammar.createOnigScanner (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:2578:30)
    at RegExpSourceList.compile (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:1875:38)
    at BeginEndRule.compile (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:2045:45)
    at matchRule (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:2822:28)
    at matchRuleOrInjections (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:2841:23)
    at scanNext (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:2937:17)
    at _tokenizeString (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:2930:9)
    at Grammar._tokenize (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:2680:25)
    at Grammar.tokenizeLine (/home/takeji/repos/git/e-bigmoon/vscode-language-yesod/node_modules/vscode-textmate/release/main.js:2643:22)
```

**Comment by isao-takejib** [comment]
This is a continuation of https://github.com/e-bigmoon/vscode-language-yesod/issues/27#issuecomment-846379724.

I also tried vscode-textmate versions 5.2.0 and 5.4.0.

- vscode-tmgrammar-test ver0.0.10 (+ vscode-textmate ver5.2.0)
    - See [Developing.md](https://github.com/PanAeon/vscode-tmgrammar-test/blob/master/Developing.md) for instructions on how to run vscode-tmgrammar-test.
```bash
# Clone vscode-tmgrammar-test and then modify it to use vscode-textmate ver5.2.0
$ node ./dist/src/unit.js --scope source.yesod.hamlet --grammar ~/repos/git/e-bigmoon/vscode-language-yesod/syntaxes/hamlet.tmLanguage.json --grammar ~/repos/git/e-bigmoon/vscode-language-yesod/haskell.tmLanguage.json -t ~/repos/git/e-bigmoon/vscode-language-yesod/test2.hamlet
✖ testcase /home/takeji/repos/git/e-bigmoon/vscode-language-yesod/test2.hamlet aborted due to an error
Error: invalid pattern in look-behind
    at Object.createOnigScanner (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/dist/src/unit/index.js:120:60)
    at e.createOnigScanner (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:6141)
    at new e (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:29784)
    at e.compile (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:34398)
    at t.compile (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:37822)
    at /home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:9808
    at R (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:10242)
    at f (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:12144)
    at S (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:11997)
    at e._tokenize (/home/takeji/repos/git/other/vscode-tmgrammar-test_txmt5.2/node_modules/vscode-textmate/release/main.js:1:8354)
```
- vscode-tmgrammar-test ver0.0.10 (+ vscode-textmate ver5.4.0)
```bash
# Clone vscode-tmgrammar-test and then modify it to use vscode-textmate ver5.2.0
$ node ./dist/src/unit.js --scope source.yesod.hamlet --grammar ~/repos/git/e-bigmoon/vscode-language-yesod/syntaxes/hamlet.tmLanguage.json --grammar ~/repos/git/e-bigmoon/vscode-language-yesod/haskell.tmLanguage.json -t ~/repos/git/e-bigmoon/vscode-language-yesod/test2.hamlet
✓ /home/takeji/repos/git/e-bigmoon/vscode-language-yesod/test2.hamlet run successfuly.
```

**Comment by isao-takejib** [comment]
I submitted a pull request to `vscode-tmgrammar-test`.

https://github.com/PanAeon/vscode-tmgrammar-test/pull/24
